### ISSUE TITLE
Source code? 

### ISSUE THREAD

**Issue by dejac001** [CCSI-Toolset/membrane_model#11]
I'm not seeing any source code in this repository, just documentation. Am I missing something?

**Comment by ksbeattie** [comment]
Hi @dejac001, the [HFGP.acmf](https://github.com/CCSI-Toolset/membrane_model/blob/master/HFGP.acmf) file is the source code for this model - which runs within ACM (Aspen Custom Modeler).  The details of how to run it within ACM should be in the docs, specifically the "4.0 Tutorial" section.
