### ISSUE TITLE
lack the unit conversion of viscosity (bar*h) into (bar*s)

### ISSUE THREAD

**Issue by KunXin666** [CCSI-Toolset/membrane_model#6]
https://github.com/CCSI-Toolset/membrane_model/blob/9eac43ec5696d3851b77d716f2afaa04a346f05b/HFGP.acmf#L185

when calculating the pressure drop in shell side, the unit of velocity is m/s, so for the viscosity (bar*h) should be adjusted to bar*s  

Pret(x).ddx = -8*nuret(x)`*3600`*Vret(x)/((d_e/2)^2);

the same problem in the codes without sweep gas

**Comment by ksbeattie** [comment]
@KunXin666l, thanks for the input.  I'm reaching out to other developers on getting your suggested change incorporated in.

**Comment by KunXin666** [comment]
Dear Keith, noted with many thanks.

Best regards,
Kun


Kun Xin

PhD candidate


[cid:062cee5c-e0c0-4b7a-b7bf-5a1c232f2ee7]


Chemical Process Intensification (SPI)

Multiphase reactors (SMR)

Dept. Chemical Engineering and Chemistry (ST)



Building 14, Helix (room STW 0.56)

Het Kranenveld

5612 AJ Eindhoven

________________________________

**Comment by ksbeattie** [comment]
@KunXin666l, this should be fixed now.  It will be in the next release.  For the details of the fix (which ended up not being your exact suggestion) see PR #7
